### ISSUE TITLE
Need a contribution.md file

### ISSUE THREAD

**Issue by Dirac156** [ALUDeveloperStudentClub/alu-map#1]
The file will contain guidelines and best practices we should follow for the pull request to be accepted and merged into the main project.

**Comment by idrismusa4** [comment]
Assign to me

**Comment by Pragya2056** [comment]
I have worked on it and opened a pull request. Please Check!!

**Comment by Pragya2056** [comment]
@https://github.com/ALUDeveloperStudentClub/alu-map/pull/3

**Comment by Dirac156** [comment]
Great @Pragya2056. Let me review the pull request.

**Comment by Pragya2056** [comment]
Please also check #4 . 
There are the code of conducts for the repo. 
Thank you!!

**Comment by Dirac156** [comment]
Yes, I saw it and it is great. I will soon post some issues and tasks.

**Comment by Dirac156** [comment]
I am going to close this issue. Hope to see more of your pull requests.
