### ISSUE TITLE
Setup docker image for mongodb and configure mongoose.

### ISSUE THREAD

**Issue by Dirac156** [ALUDeveloperStudentClub/alu-map#20]
Steps:

Create an appconfig.js file under config folder.
export object appconfig file (collection of all configurations).

The appconfig file will contain app config, database config, ...

`const appconfigfile = {
    db: {
        uri: MONGO_DB_URI (from .env || docker_img)
    }
}
`

use the URI to connect to the database.
log mongodb events.

**Comment by Freedisch** [comment]
@Dirac156 I want to work on it

**Comment by Dirac156** [comment]
great @Freedisch . Assigned
