### ISSUE TITLE
client + documentation: come up with a simple ui template

### ISSUE THREAD

**Issue by Dirac156** [ALUDeveloperStudentClub/alu-map#25]
Components:

- Search engine field where some can look for a room.
- A Result field when data is found or not.
- Admin authentication.
- Form to add a new room: Refer to ALU rooms (Floor, common, name, ...)
- Form to add a new common.

Add the link to the prototype on the README.md file.
Add the section containing the prototype file into the table of content.

**Comment by John-Daniels** [comment]
i can give it a try

**Comment by Dirac156** [comment]
okay @John-Daniels

**Comment by John-Daniels** [comment]
Hey @Dirac156 do you have a figma design for this project... it will really help alot

**Comment by Dirac156** [comment]
Hii @John-Daniels . The UI will come from us. Thanks.
