### ISSUE TITLE
Landing page/Documentation for new contributors

### ISSUE THREAD

**Issue by Perfectizihirwe** [ALUDeveloperStudentClub/alu-map#36]
<p>This page will help new contributors know how to get started with this project instead of landing on the default React page. It also has links to necessary tools like Docker, Hyper-V and Issues section of this repo. I need access to push it @Dirac156 </p>
<img width="947" alt="Screenshot_20221021_115410" src="https://user-images.githubusercontent.com/98801724/197295029-4de0d8ba-d66e-432f-9b81-fb1f036d8ec0.png" />

**Comment by Dirac156** [comment]
@Perfectizihirwe did you fork the repository?

**Comment by Perfectizihirwe** [comment]
I only cloned it.

**Comment by Perfectizihirwe** [comment]
Issue closed, landing page PR raised
