### ISSUE TITLE
Configure ExpressJS web server to run on port 8000.

### ISSUE THREAD

**Issue by Dirac156** [ALUDeveloperStudentClub/alu-map#7]

**Comment by nirajpdn** [comment]
I want to work on this, assign this issue to me.

**Comment by nirajpdn** [comment]
Javascript or typescript ?

**Comment by Dirac156** [comment]
Yes the project is in javascript.

**Comment by Dirac156** [comment]
@nirajpdn

**Comment by Dirac156** [comment]
Hi @nirajpdn. is it possible to update the server code to import instead of requiring modules?

**Comment by nirajpdn** [comment]
@Dirac156 yes, it is possible. I will create issue and assign that issue to me.
